### PR TITLE
📦 NEW: create ADO pipeline example

### PR DESCRIPTION
**Pull request by tallguyjenks**
Just made this from scratch yesterday and got it functioning in my Government Agencies ADO instance. 

Related:

- #318 
- #401

### CODE REVIEW

**Comment by tallguyjenks** [comment]
Hello! 

Is there anything I need to do to make this easier for review?

**Comment by jeffwidman** [comment]
Sorry for the radio silence here.

I realize this PR is nearly a year old, is this code still working for you? Anything need updating before I merge it?

**Comment by tallguyjenks** [comment]
hey! no worries, we're all busy :) 
no edits needed, its still runs as is in our environment :)
good to merge!

**Review by jeffwidman — APPROVED** [review]
Thanks again!

**Pull request merged**
