### PR TITLE
bump Ruby version in Gemfile.lock to 2.6.6

### PR DESCRIPTION
**Pull request by RogierW**

### CODE REVIEW

**Comment by RogierW** [comment]
For more information about the latest commit; https://github.com/dependabot/dependabot-script/issues/453.

**Comment by carlbordum** [comment]
These changes would be very helpful for me. Can you take a look @feelepxyz?

**Comment by feelepxyz** [comment]
Thanks for this, I've updated main with the latest version of dependabot and removed the requirement on an exact ruby version.

**Comment by carlbordum** [comment]
Thank you very much!

**Pull request closed without merging**
