### PR TITLE
Add batching dependency updates in pull requests

### PR DESCRIPTION
**Pull request by some-natalie**
Add batching dependency updates to pull requests!

This should address dependabot/dependabot-core#1190 

This PR adds `batch-size` to `~/.github/dependabot.yml`.  If not set, it'll default to `1` and Dependabot-script will work as it usually does - 1 pull request per dependency to update.  If it is set to something greater than `1`, it'll batch updates within the same manifest file and ecosystem up to that size.

This also bumps dependabot-core and associated dependencies to 0.158.0

Here's a screenshot of it in action on GitHub Enterprise Server:
Screen Shot 2021-06-24 at 8 19 11 AM

Here's a sample `~/.github/dependabot.yml` file that includes setting and not setting the `batch-size` parameter:
```
---
version: 2
updates:
  - package-ecosystem: npm_and_yarn
    directory: "/javascript"
    schedule:
      interval: daily
    batch-size: 5
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/python"
    schedule:
      interval: weekly
    batch-size: 5
```

### CODE REVIEW

**Comment by roancath** [comment]
I noticed the source branch that's being created for the PR is a combination of all the packages that will be updated. Can this be changed into a shorter name so we can set the batch size to higher number like 20? Thanks!

**Comment by Somersall-Natalie** [comment]
@roancath , that's a fantastic idea!  I'm sorry it took me so long to make the change, but the latest commit does exactly that for _only_ the branch name.  I was still thinking the PR name should be long for fast visual "oh, this is a big PR" and the name limitation there is a decent amount bigger, however, we could truncate this too.

Here's what it looks like in GHES with a giant batch size:
Screen Shot 2021-08-11 at 9 26 05 AM

**Comment by roancath** [comment]
@Somersall-Natalie this is awesome! thanks so much for this!

**Comment by roancath** [comment]
@Somersall-Natalie been testing this out and I noticed that the batching PR doesn't support multiple files for nuget package manager type. For example, there are multiple projects in a dotnet solution and let's say projectA.csproj would reference and include dependencies from projectB.csproj. 

**projectA.csproj:**
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.8.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.2.0" />
    <PackageReference Include="Microsoft.Azure.Storage.Blob" Version="11.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\projectB\projectB.csproj" />
  </ItemGroup>

</Project>
```

When dependabot runs on projectA, it's able to process all dependencies from both projectA and projectB since projectA is referencing projectB in it's .csproj file. However, the PR will only update projectB.csproj because that's the last file that it was able to process. Do you have some thoughts on how to resolve this?

**Comment by Somersall-Natalie** [comment]
Hey @roancath, I'm sorry I haven't been terribly responsive here.  I do not have any ideas on how to resolve this, but I'm also unsure what the ask is.  I don't work with nuget, so would love some clarification here.  Is this an accurate representation of what's going on?

```
manifest-file-1
├─ dependency-a
├─ dependency-b
├─ dependency-c
├─ manifest-file-2
│  ├─ dependency-alpha
│  ├─ dependency-beta
├─ manifest-file-3
│  ├─ dependency-one
│  ├─ dependency-two
│  ├─ dependency-three
├─ dependency-d
```

In this case, if you set the batch size to 10 and assuming all the dependencies are out of date, are you expecting one pull request with all 9 dependencies in it?  

I ran that past a few of our development teams that use this internally and they were all _extremely_ against it.  The short version of some very long chat messages was that dependencies get grouped by manifests for all sorts of reasons, but they're handled in different files for a reason and shouldn't be "bridged" across in one PR.  Pull requests are free and compute to run the CI tests is cheap, so the preferred workflow was to handle all of the sub-manifests individually, then the ones in root manifest file.

However, I also have no idea why this is the case and would love to dig into it when I get the chance. :)

**Comment by jeffwidman** [comment]
Thanks for submitting! And sorry for the radio silence here. I joined the team recently and trying to catch up on older PRs.

Wow this is impressive, a lot of work went into this!

I'm afraid I'm going to close this though, for the rationale explained in https://github.com/dependabot/dependabot-script/pull/340#issuecomment-532723863.

This is a feature we've thought about adding into Dependabot core itself... see:
* https://github.com/dependabot/dependabot-core/issues/1190#issuecomment-1071367790
* https://github.com/github/roadmap/issues/148

So if we get this built into `dependabot-core`, then there'll be no need for this PR beyond parsing some configs. And for those, we'd most likely go with a pattern of parsing [`dependabot.yml`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) to keep things consistent.

**Pull request closed without merging**
