### PR TITLE
Use GitHub Actions as runner for CI

### LINKED ISSUE #320: CI tests
I suggest setting up some form of CI tests for this project so issues like the one in #319 get caught sooner, ideally before getting merged.

### PR DESCRIPTION
**Pull request by LeoColomb**
Closes #320

Basically checks the script runs.
It would catch any version mismatch with the docker image or huge syntax errors on the main script.
Could definitely be extended, but I let's start with a minimal set.

### CODE REVIEW

**Comment by greysteil** [comment]
Oh nice. let's give it a try!

**Comment by greysteil** [comment]
Hmmm, looks like the first run has hit a bug: https://github.com/dependabot/dependabot-script/commit/80806e2718c4ac2dfe005b9978ed485d44cb143e/checks

I think that's a bug with actions, so will ping the GitHub team responsibe.

**Comment by LeoColomb** [comment]
@greysteil Did you set [the `GITHUB_TOKEN`](https://github.com/dependabot/dependabot-script/blob/80806e2718c4ac2dfe005b9978ed485d44cb143e/.github/workflows/run.yml#L27) variable? Should be there: https://github.com/dependabot/dependabot-script/settings/secrets

**Comment by greysteil** [comment]
I thought it was a magic one? If I try to add a secret with that name I get an error.

image

**Comment by LeoColomb** [comment]
Ah, [you're right](https://help.github.com/en/articles/virtual-environments-for-github-actions#github_token-secret)! 😇

**Pull request merged**
