### PR TITLE
Add a way to assign Gitlab MRs to a user

### PR DESCRIPTION
**Pull request by Bowbaq**
I've setup this script in Gitlab, everything works well except I'm not getting email notifications when `dependabot` creates MRs. This is an attempt to fix that problem.

I'm not super familiar with `dependabot` or Ruby, please let me know if there's a better way to do this.

### CODE REVIEW

**Comment by greysteil** [comment]
Looks sensible to me. Does it work locally?

**Comment by Bowbaq** [comment]
Is there a good way to test it? I've set it up on my CI, but all my dependencies are up to date at the moment, so I'll have to wait a bit.

**Comment by greysteil** [comment]
Not if all your dependencies are up-to-date! I think we're fine to merge this, though - let me know if anything breaks.

**Comment by schliflo** [comment]
Trying to run this with Docker `dependabot/dependabot-core` I get this error:
```bash
$ bundle exec ruby /static/generic-update-script.rb
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.3-compliant syntax, but you are running 2.6.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Fetching bundler dependency files for schliflo/dependabot-docker
Parsing dependencies information
  - Updating dependabot-omnibus (from 0.111.6)…/builds/schliflo/dependabot-docker/vendor/ruby/2.6.0/gems/dependabot-common-0.111.6/lib/dependabot/pull_request_creator.rb:26:in `initialize': unknown keyword: assignee (ArgumentError)
	from /static/generic-update-script.rb:173:in `new'
	from /static/generic-update-script.rb:173:in `block in <main>'
	from /static/generic-update-script.rb:130:in `each'
	from /static/generic-update-script.rb:130:in `<main>'
```
This exact setup was functional before updating `generic-update-script.rb`

Maybe this needs some more testing after all? 
What happens if `GITLAB_ASSIGNEE_ID` is not set?

**Comment by greysteil** [comment]
Yeah, this should be `assignees`. I'll fix.

**Comment by greysteil** [comment]
Fixed.

**Comment by schliflo** [comment]
Fix confirmed, thank you @greysteil 👍

**Pull request merged**
